# Generated by Django 5.2.5 on 2025-08-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("pet", "0001_initial"), ("users", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PetHealthInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation", models.TextField()),
                ("diagnosis", models.TextField()),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_info",
                        to="users.doctor",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_info",
                        to="pet.pet",
                    ),
                ),
            ],
        )
    ]
